apps/pedido/urls.py
from django.urls import path

from .views import ListarMenuesSolicitados, Pedido, PedidoAdmin, PedidoCliente, addTipo_Plato, agregar_Menu_detalle, agregar_Menu_procesar_compra, cambiarEstadoPedidoyComentar, deleteTipo_plato, listTipo_Menu, listTipo_Plato, listar_pedidos_clientes, listar_pedidos_por_fecha, \
    modificarTipo_Plato, Menu_pagina_principal, \
     \
    detalleMenu, addMenu, menuxCategoria, editarMenu, deleteMenu, listarMenues, addTipo_Menu, \
    modificarTipo_Menu, deleteTipo_Menu, registroPedido, todos_los_pedido_lista, viewcart, agregar_Menu, eliminar_Menu, restar_Menu, cleancart, procesar_compra, estadisticas, asignarRepartidor

app_name = 'pedido'

urlpatterns = [

    path('menu/', Menu_pagina_principal, name='Menu_pagina_principal'),
    path('agregar_Menu_procesar_compra/<producto_id>',
         agregar_Menu_procesar_compra, name="agregar_Menu_procesar_compra"),

    path('tipo_menu/', listTipo_Menu, name='tipo_menu'),

    path('tipo_plato/', listTipo_Plato, name='tipo_plato'),

    path('addTipo_Plato/', addTipo_Plato, name='addTipo_Plato'),

    path('modificarTipo_Plato/<id>', modificarTipo_Plato,
         name='modificarTipo_Plato'),

    path('deleteTipo_plato/<id>', deleteTipo_plato, name='deleteTipo_plato'),

    path('addTipo_Menu/', addTipo_Menu, name='addTipo_Menu'),

    path('modificarTipo_Menu/<id>', modificarTipo_Menu, name='modificarTipo_Menu'),

    path('deleteTipo_Menu/<id>', deleteTipo_Menu, name='deleteTipo_Menu'),

    path('detalle/', detalleMenu, name='detalle'),

    path('addMenu/', addMenu, name='addMenu'),

    path('menuxCategoria/<id>/', menuxCategoria, name='menuxCategoria'),

    path('editarMenu/<id>/', editarMenu, name='editarMenu'),

    path('deleteMenu/<id>/', deleteMenu, name='deleteMenu'),

    path('listarMenues/', listarMenues, name='listarMenues'),


    path('viewcart/', viewcart, name="viewcart"),

    path('agregar_Menu/<producto_id>', agregar_Menu, name="agregar_Menu"),


    path('delcart/<producto_id>', eliminar_Menu, name="delcart"),

    path('restarcart/<producto_id>', restar_Menu, name="restarcart"),

    path('cleancart/', cleancart, name="cleancart"),

    path('procesar_compra/', procesar_compra, name="procesar_compra"),

    path('registroPedido/', registroPedido, name="registroPedido"),
    path('pedidoCliente/', PedidoCliente, name="pedidoCliente"),



    path('PedidoAdmin/', PedidoAdmin, name="PedidoAdmin"),


    path('listar_pedidos_clientes/', listar_pedidos_clientes,
         name="listar_pedidos_clientes"),

    path('todos_los_pedido_lista/', todos_los_pedido_lista,
         name="todos_los_pedido_lista"),





    path('cambiarEstadoPedidoyComentar/<int:pedido_id>',
         cambiarEstadoPedidoyComentar, name="cambiarEstadoPedidoyComentar"),

    path('estadisticas/', estadisticas, name="estadisticas"),

    path('listar_pedidos_por_fecha', listar_pedidos_por_fecha,
         name="listar_pedidos_por_fecha"),

    path('ListarMenuesSolicitados', ListarMenuesSolicitados,
         name="ListarMenuesSolicitados"),



    path('asignarRepartidor/<id>', asignarRepartidor, name='asignarRepartidor'),




]

rotiseriaelmejorsabor/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/index.html'), name='inicio'),
    path('inicio_admin/', TemplateView.as_view(template_name='base/index_admin.html'),
         name='inicio_admin'),
    path('persona/', include('apps.persona.urls', namespace='persona')),
    path('persona/cliente', include('apps.persona.urls', namespace='cliente')),
    path('persona/empleado', include('apps.persona.urls', namespace='empleado')),


    path('menu/', include('apps.pedido.urls', namespace='menu')),
    path('menu/compra/', include('apps.pedido.urls', namespace='compra')),
    path('pedido/', include('apps.pedido.urls', namespace='pedido')),

    path('usuario/', include('apps.usuario.urls', namespace='usuario')),

    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pedido/forms.py
from django import forms
from django.forms import DateInput, ModelForm
from .models import Menu, Pedido, Tipo_Menu, Tipo_Plato

from apps.persona.models import *


class nuevoMenuForm(forms.ModelForm):
    class Meta:
        model = Menu

        fields = (
            "nombre", "precio", "descripcion", "tipo_menu", "tipo_plato", "imagen")


class nuevoTipoMenuForm(forms.ModelForm):
    class Meta:
        model = Tipo_Menu
        fields = ["nombre"]


class nuevoTipoPlatoForm(forms.ModelForm):
    class Meta:
        model = Tipo_Plato
        fields = ["nombre"]


class DateInput(forms.DateInput):
    input_type = 'date'


class TimePickerInput(forms.TimeInput):
    input_type = 'time'


class PedidoForm(ModelForm):
    class Meta:
        model = Pedido
        fields = ('cliente', 'fechaPedido', 'horaEntrega', 'TipoEntrega', 'Estado', 'menu',
                  'repartidor')

        widgets = {
            'fechaPedido': DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
            'horaEntrega': TimePickerInput(),

        }

    def __init__(self, *args, **kwargs):
        super(PedidoForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class PedidoClienteForm(ModelForm):
    class Meta:
        model = Pedido
        exclude = ('fechaPedido', 'horaEntrega' 'Estado',
                   'repartidor', 'cliente', 'menu', 'comentario')

    def __init__(self, *args, **kwargs):
        super(PedidoClienteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ActualizarPedidoForm(forms.Form):
    ESTADO_OPCIONES = (
        (1, "Pendiente"), (2, "En preparación"), (3,
                                                  "En camino"), (4, "Entregado"), (5, "Devuelto"),
        (6, "Cancelado"))

    estadoPedido = forms.ChoiceField(choices=ESTADO_OPCIONES, label=False)
    comentario = forms.CharField(max_length=500, label=False)

# class RepartidorForm(forms.Form):
#     class Meta:
#         model = Repartidor

#         fields = ('CUIT', 'apellido', 'nombre', 'celular', 'telefono_fijo', 'fecha_nacimiento', 'calle', 'numero', 'localidad', 'departamento', 'observaciones', 'fecha_ingreso_trabajar', 'vigencia_carnet', 'patente', 'zona')


class DateRangeForm(forms.Form):
    Fecha_desde = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    Fecha_hasta = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))

    def __init__(self, *args, **kwargs):
        super(DateRangeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['type'] = 'date'


class DateRangeCadeteForm(forms.Form):
    Fecha_desde = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    Fecha_hasta = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    Cadete = forms.ModelChoiceField(queryset=Repartidor.objects.all())

    def __init__(self, *args, **kwargs):
        super(DateRangeCadeteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['type'] = 'date'

apps/pedido/views.py
import datetime
from operator import itemgetter
from django.http import Http404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, permission_required
from .forms import DateRangeForm, DateRangeCadeteForm
from apps.pedido.carro import Carro
from apps.persona.models import Repartidor
from .forms import ActualizarPedidoForm, PedidoClienteForm, PedidoForm, nuevoMenuForm, nuevoTipoMenuForm, nuevoTipoPlatoForm
from .models import Pedido, Estado, Menu, Tipo_Plato, Tipo_Menu
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator


def compra(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/compra.html')


def estadisticas(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/estadisticas.html')


def estado_pedido(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/estado_pedido.html')


def orden_compra(request):
    return render(request, 'pedido/orden_compra.html')


def pedidos_vista_admin(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/pedidos_vista_admin.html')


def menu(request):
    return render(request, 'pedido/menu.html')


####################################################################################


def listar_menu(request):
    return render(request, 'pedido/listar_menu.html', {'menus': Menu.objects.all()})


def gestion_menu(request):
    if request.user.is_authenticated and request.user.is_staff:
        if (request.method == "POST"):
            menu = nuevoMenuForm(request.POST)

            for field in menu:
                print("Field Error:", field.name, field.errors)

            if (menu.is_valid()):
                nuevo_menu = menu.save()
                nuevo_menu.save()

                messages.success(request, 'Se ha agregado correctamente el menu {}'.format(
                    nuevo_menu))
                return redirect('pedido:gestion_menu')

        else:
            menu = nuevoMenuForm()

        return render(request, 'pedido/gestion_menu.html', {'menu': menu})


def eliminar_menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        menu = get_object_or_404(Menu, id=id)
        menu.delete()
        return redirect(to='pedido:listar_menu')


def modificar_menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        menu = get_object_or_404(Menu, id=id)
        data = {
            'menu': nuevoMenuForm(instance=menu)
        }
        if (request.method == "POST"):

            formulario = nuevoMenuForm(

                data=request.POST, instance=menu, files=request.FILES)

            if formulario.is_valid():
                formulario.save()
                data["mensaje"] = "Modificacion correcta"

                return redirect(to="pedido:listar_menu")

            data["menu"] = formulario

        return render(request, 'pedido/modificar_menu.html', data)


##########################################################################################


def gestion_plato(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/gestion_plato.html')


def gestion_ingrediente(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/gestion_Ingrediente.html')


############################################################################################




def Menu_pagina_principal(request):
    busqueda = request.POST.get("buscador")
    product_list = Menu.objects.order_by('nombre')
    page = request.GET.get('page', 1)

    if busqueda:
        product_list = Menu.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    try:
        paginator = Paginator(product_list, 12)
        product_list = paginator.page(page)
    except:
        raise Http404

    data = {'entity': product_list,
            'paginator': paginator
            }
    return render(request, 'pedido/menuDeComidas.html', data)



def menuxCategoria(request, id):
    busqueda = request.POST.get("buscador")
    lista_productos = Menu.objects.filter(tipo_menu=id)

    if busqueda:
        lista_productos = Menu.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    data = {'entity': lista_productos}
    return render(request, 'pedido/menuDeComidas.html', data)


def detalleMenu(request, id):
    menu = get_object_or_404(Menu, id=id)
    otrosProductos = Menu.objects.filter(tipo_menu=menu.tipo_menu)
    data = {
        'menu': menu,
        'productosRelacionados': otrosProductos
    }
    return render(request, 'pedido/menu/detalle.html', data)


@login_required(login_url='/login')
def addMenu(request):
    data = {
        'form': nuevoMenuForm()
    }

    if request.method == 'POST':
        formulario = nuevoMenuForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="pedido:listarMenues")
        else:
            data["form"] = formulario
    return render(request, 'pedido/menu/agregar.html', data)


def listarMenues(request):
    if request.user.is_authenticated and request.user.is_staff:
        busqueda = request.POST.get("buscador")
        lista_productos = Menu.objects.order_by('nombre')
        page = request.GET.get('page', 1)
        if busqueda:
            lista_productos = Menu.objects.filter(
                Q(nombre__icontains=busqueda) |
                Q(descripcion__icontains=busqueda)
            ).distinct()

        try:
            paginator = Paginator(lista_productos, 6)
            lista_productos = paginator.page(page)
        except:
            raise Http404

        data = {'entity': lista_productos,
                'title': 'LISTADO DE MENUES',
                'paginator': paginator
                }
        return render(request, 'pedido/menu/listar.html', data)


def editarMenu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        menu = get_object_or_404(Menu, id=id)
        data = {
            'form': nuevoMenuForm(instance=menu)
        }

        if request.method == 'POST':
            formulario = nuevoMenuForm(
                data=request.POST, instance=menu, files=request.FILES)
            if formulario.is_valid():
                formulario.save()
                messages.success(request, "Registro modificado correctamente")
                return redirect(to="pedido:listarMenues")
            data["form"] = formulario
        return render(request, 'pedido/menu/modificar.html', data)


def deleteMenu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        producto = get_object_or_404(Menu, id=id)
        producto.delete()
        messages.success(request, "Registro eliminado correctamente")
        return redirect(to="pedido:listarMenues")

@permission_required('pedido.view_Tipo_Menu', login_url="usuario:login")
def listTipo_Menu(request):
    lista_categorias = Tipo_Menu.objects.all().order_by('nombre')
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(lista_categorias, 6)
        lista_categorias = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_categorias,
            'title': 'Tipo De Menu',
            'paginator': paginator
            }

    return render(request, 'pedido/tipo_menu.html', data)

@permission_required('pedido.add_Tipo_Menu', login_url="usuario:login")
def addTipo_Menu(request):
    if request.user.is_authenticated and request.user.is_staff:
        data = {
            'form': nuevoTipoMenuForm()
        }
        if request.method == 'POST':
            formulario = nuevoTipoMenuForm(data=request.POST)

            if formulario.is_valid():
                formulario.save()
                messages.success(request, "Registro agregado correctamente")
                return redirect(to="pedido:tipo_menu")
            else:
                data["form"] = formulario
        return render(request, 'pedido/tipo_menu/agregar_tipo_menu.html', data)

@permission_required('pedido.change_Tipo_Menu', login_url="usuario:login")
def modificarTipo_Menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        tipo_menu = get_object_or_404(Tipo_Menu, id=id)

        data = {
            'form': nuevoTipoMenuForm(instance=tipo_menu)
        }
        if request.method == 'POST':
            formulario = nuevoTipoMenuForm(
                data=request.POST, instance=tipo_menu)
            if formulario.is_valid():
                formulario.save()
                messages.success(request, "Registro modificado correctamente")
                return redirect(to="pedido:tipo_menu")
            else:
                data["form"] = formulario

        return render(request, 'pedido/tipo_menu/modificar_tipo_menu.html', data)

@permission_required('pedido.delete_Tipo_Menu', login_url="usuario:login")
def deleteTipo_Menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        categoria = get_object_or_404(Tipo_Menu, id=id)
        categoria.delete()
        messages.success(request, "Registro eliminado correctamente")
        return redirect(to="pedido:tipo_menu")


def listTipo_Plato(request):
    if request.user.is_authenticated and request.user.is_staff:

apps/pedido/templates/pedido/carrito/cart.html
{% extends 'base/menu_rotiseria.html' %} {% block content %}
{% load static %}

<link rel="stylesheet" href="{%static  '/css/cart.css' %}">


<div class="">
    <div class="" style="text-align: center;">
        <div class="row ">
            <div class="col-lg-9 col-md-8 col-sm-6 mx-auto columna ">

                <div class="card">
                    <div class="card-header text-center">
                        <strong>CARRITO</strong>
                    </div>
                    <div class="card body p-2">
                        {% load humanize %}
                        <h6 style="color: black;">Total: <strong>
                                $. {{ importe_total_carro | intcomma }}
                            </strong></h6>

                    </div>

                    <div class="card-element table-responsive">
                        <table class="table table-condensed">
                            <thead class="text-center">
                                <tr>
                                    <th>Item</th>
                                    <th colspan="3">Cantidad</th>
                                    <th>Subtotal</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tbody class="py-4">
                                {% if request.session.carro.items %} {% for key, value in request.session.carro.items %}
                                <tr>
                                    <td>{{ value.nombre }}</td>

                                    {% load bootstrap_icons %}
                                    <td class="text-center" colspan="3">
                                        {{ value.cantidad }}
                                        <a href="{% url 'pedido:agregar_Menu_procesar_compra' value.producto_id %}"
                                            class="btn btn-success btn-sm" type="button"><i class="bi bi-plus"></i></a>




                                        <a class="btn btn-danger btn-sm"
                                            href="{% url 'pedido:restarcart' value.producto_id %}" type="button"><i
                                                class="bi bi-dash"></i> </a>
                                    </td>

                                    <td class="text-center">$.{{ value.precio }} </td>
                                    <td class="text-center">
                                        <a class="btn btn-info btn-sm"
                                            href="{% url 'pedido:delcart' value.producto_id %}" type="button"><i
                                                class="bi bi-trash"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <tr>
                                    <td colspan="5">
                                        <div class="alert alert-danger text-center ">

                                            No se agregaron productos al carrito

                                        </div>
                                </tr>
                                </tr>
                                {% endif %}

                            </tbody>
                        </table>

                    </div>

                    <div class="card-footer mx-auto ">

                        {% if user.is_authenticated and user.is_superuser %}

                        <a class="btn btn-danger mx-auto mt-0 " href="{% url 'pedido:PedidoAdmin'%}">Procesar Compra
                            </a>

                        {% else %}

                        {% if request.session.carro.items   %}



                        <a class="btn btn-danger mx-auto mt-0 " href="{% url 'pedido:pedidoCliente'%}">Procesar
                            Compra</a>
                        {% else %}
                        <a class="btn btn-danger mx-auto mt-0 disabled" href="#">Procesar Compra</a>
                        {% endif %}

                        {% endif %}

                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-3 my-4 mx-auto ">
                <div class="card card-footer align-item-center ">
                    <a href="{% url 'pedido:Menu_pagina_principal' %}" class="btn btn-warning my-2 mx-auto ">Volver Al
                        Menu</a>
                    <a href="{% url 'pedido:cleancart' %}" class="btn btn-primary my-2 mx-auto ">Limpiar Carrito</a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}