apps/pedido/urls.py
from django.urls import path

from .views import ListarMenuesSolicitados, Pedido, PedidoAdmin, PedidoCliente, addTipo_Plato, agregar_Menu_detalle, agregar_Menu_procesar_compra, cambiarEstadoPedidoyComentar, deleteTipo_plato, listTipo_Menu, listTipo_Plato, listar_pedidos_clientes, listar_pedidos_por_fecha, \
    modificarTipo_Plato, Menu_pagina_principal, \
     \
    detalleMenu, addMenu, menuxCategoria, editarMenu, deleteMenu, listarMenues, addTipo_Menu, \
    modificarTipo_Menu, deleteTipo_Menu, registroPedido, todos_los_pedido_lista, viewcart, agregar_Menu, eliminar_Menu, restar_Menu, cleancart, procesar_compra, estadisticas, asignarRepartidor

app_name = 'pedido'

urlpatterns = [

    path('menu/', Menu_pagina_principal, name='Menu_pagina_principal'),
    path('agregar_Menu_procesar_compra/<producto_id>',
         agregar_Menu_procesar_compra, name="agregar_Menu_procesar_compra"),

    path('tipo_menu/', listTipo_Menu, name='tipo_menu'),

    path('tipo_plato/', listTipo_Plato, name='tipo_plato'),

    path('addTipo_Plato/', addTipo_Plato, name='addTipo_Plato'),

    path('modificarTipo_Plato/<id>', modificarTipo_Plato,
         name='modificarTipo_Plato'),

    path('deleteTipo_plato/<id>', deleteTipo_plato, name='deleteTipo_plato'),

    path('addTipo_Menu/', addTipo_Menu, name='addTipo_Menu'),

    path('modificarTipo_Menu/<id>', modificarTipo_Menu, name='modificarTipo_Menu'),

    path('deleteTipo_Menu/<id>', deleteTipo_Menu, name='deleteTipo_Menu'),

    path('detalle/', detalleMenu, name='detalle'),

    path('addMenu/', addMenu, name='addMenu'),

    path('menuxCategoria/<id>/', menuxCategoria, name='menuxCategoria'),

    path('editarMenu/<id>/', editarMenu, name='editarMenu'),

    path('deleteMenu/<id>/', deleteMenu, name='deleteMenu'),

    path('listarMenues/', listarMenues, name='listarMenues'),


    path('viewcart/', viewcart, name="viewcart"),

    path('agregar_Menu/<producto_id>', agregar_Menu, name="agregar_Menu"),


    path('delcart/<producto_id>', eliminar_Menu, name="delcart"),

    path('restarcart/<producto_id>', restar_Menu, name="restarcart"),

    path('cleancart/', cleancart, name="cleancart"),

    path('procesar_compra/', procesar_compra, name="procesar_compra"),

    path('registroPedido/', registroPedido, name="registroPedido"),
    path('pedidoCliente/', PedidoCliente, name="pedidoCliente"),



    path('PedidoAdmin/', PedidoAdmin, name="PedidoAdmin"),


    path('listar_pedidos_clientes/', listar_pedidos_clientes,
         name="listar_pedidos_clientes"),

    path('todos_los_pedido_lista/', todos_los_pedido_lista,
         name="todos_los_pedido_lista"),





    path('cambiarEstadoPedidoyComentar/<int:pedido_id>',
         cambiarEstadoPedidoyComentar, name="cambiarEstadoPedidoyComentar"),

    path('estadisticas/', estadisticas, name="estadisticas"),

    path('listar_pedidos_por_fecha', listar_pedidos_por_fecha,
         name="listar_pedidos_por_fecha"),

    path('ListarMenuesSolicitados', ListarMenuesSolicitados,
         name="ListarMenuesSolicitados"),



    path('asignarRepartidor/<id>', asignarRepartidor, name='asignarRepartidor'),




]

apps/persona/urls.py
from django.urls import path

from . import views
from .views import creacion_cliente, listar_clientes, modificar_cliente, creacion_empleado, listar_empleados, eliminar_cliente, modificar_empleado, eliminar_empleado, listar_repartidores, modificar_repartidor, eliminar_repartidor

app_name = 'persona'

urlpatterns = [
    path('registrar_cliente/', creacion_cliente, name='registrar_cliente'),

    path('listar_clientes/', listar_clientes, name='listar_clientes'),

    path('modificar_cliente/<id>', modificar_cliente, name='modificar_cliente'),

    path('registrar_empleado/', views.creacion_empleado, name='registrar_empleado'),

    path('creacion_repartidor/', views.creacion_repartidor,
         name='creacion_repartidor'),

    path('listar_empleados/', listar_empleados, name='listar_empleados'),

    path('modificar_empleado/<id>', modificar_empleado, name='modificar_empleado'),


    path('eliminar_cliente/<id>', eliminar_cliente, name='eliminar_cliente'),

    path('eliminar_empleado/<id>', eliminar_empleado, name='eliminar_empleado'),



    ####################


    path('listar_repartidores/', listar_repartidores, name='listar_repartidores'),

    path('modificar_repartidor/<id>', modificar_repartidor,
         name='modificar_repartidor'),


    path('eliminar_repartidor/<id>', eliminar_repartidor,
         name='eliminar_repartidor'),



    ###############


]

apps/usuario/urls.py
from django.urls import path

from apps.usuario import views

app_name = 'usuario'
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("registro/", views.registro, name="registro"),
]

rotiseriaelmejorsabor/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/index.html'), name='inicio'),
    path('inicio_admin/', TemplateView.as_view(template_name='base/index_admin.html'),
         name='inicio_admin'),
    path('persona/', include('apps.persona.urls', namespace='persona')),
    path('persona/cliente', include('apps.persona.urls', namespace='cliente')),
    path('persona/empleado', include('apps.persona.urls', namespace='empleado')),


    path('menu/', include('apps.pedido.urls', namespace='menu')),
    path('menu/compra/', include('apps.pedido.urls', namespace='compra')),
    path('pedido/', include('apps.pedido.urls', namespace='pedido')),

    path('usuario/', include('apps.usuario.urls', namespace='usuario')),

    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  {% if messages %}
  {% for message in messages %}
  <script>
    alert("{{message}}");
  </script>
  {% endfor %}
  {% endif %}


  <title>

    {% block title%} TITULO DOCUMENTO {% endblock %}

  </title>

  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{%static  '/css/styles.css'%}">
  <link rel="icon" href="{%static  '/img/logo_rotiseria.png'%}">




  <link rel="stylesheet" href="{%static  '/css/admin_vista.css'%}">






  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
  </script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


  <style>
    .errorlist {



      color: red;
    }


    .nav-link,
    .usuario {
        color: #0D6EFD !important;
    }
  </style>





</head>



<!-- 
style="background-image: url({% static 'img/fondo_index_admin.jpg'%}); -->

<body  >



  {% block header%}



  {% endblock %}



  <nav style="background-color: #212529;" class="navbar navbar-expand-lg ">
    <div class="container-fluid"  style="background-color: #212529;">
      <a class="navbar-brand" href="{% url 'inicio_admin' %}"><i class="bi bi-house-door-fill"></i></a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">





          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i> Cliente
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'cliente:registrar_cliente' %}">Registrar Cliente</a></li>
              <li><a class="dropdown-item" href="{% url 'cliente:listar_clientes' %}">Listar Clientes</a></li>

            </ul>
          </li>





          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-file-earmark-person"></i> Empleados
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'empleado:registrar_empleado' %}">Registrar Empleado</a></li>
              <li><a class="dropdown-item" href="{% url 'empleado:listar_empleados' %}">Listar Empleados</a></li>
              <li><a class="dropdown-item" href="{% url 'persona:creacion_repartidor' %}">Registrar Repartidor</a></li>
              <li><a class="dropdown-item" href="{% url 'persona:listar_repartidores' %}">Listar Repartidores</a></li>

            </ul>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="/"><i class="bi bi-p-circle-fill"></i>agina <i
                class="bi bi-p-circle-fill"></i>rincipal</a>
          </li>


          <li class="nav-item">




            {% comment %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a> {% endcomment %}
            <ul class="dropdown-menu">
              {% comment %} <li><a class="dropdown-item" href="{% url 'pedido:gestion_menu' %}">Registrar Menus</a></li>
              <li><a class="dropdown-item" href="{% url 'pedido:listar_menu' %}">Listar Menu</a></li> {% endcomment %}

            </ul>
          </li>











        </ul>
      </div>
    </div>
  </nav>







  {% block content %}







  {% endblock %}



  {% block footer%}



  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <span class="text-muted">&copy; 2022 El Mejor Sabor</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-2"><a class="text-muted" href="#">
          <svg class="bi" width="24" height="24"><i class="bi bi-whatsapp"></i></svg>
        </a></li>
      <li class="ms-2"><a class="text-muted" href="#">
          <svg class="bi" width="24" height="24"><i class="bi bi-twitter"></i></svg>
        </a></li>
      <li class="ms-2"><a class="text-muted" href="#">
          <svg class="bi" width="24" height="24"><i class="bi bi-instagram"></i></svg>
        </a></li>
      <li class="ms-2"><a class="text-muted" href="#">
          <svg class="bi" width="24" height="24"><i class="bi bi-facebook"></i></svg>
        </a></li>
    </ul>
  </footer>

  {% endblock %}


</body>

</html>

templates/base/index.html
{% extends 'base_index.html'%}


{% load static %}


{% if messages %} {% for message in messages %}
<script>
  Swal.fire({
    "title": "Felicitaciones!!",
    "text": "{{ message }}",
    "icon": "success"
  })
</script>
{% endfor %} {% endif %}

{% block title%}Pagina Principal{%endblock %}











{% block header%}


<link rel="stylesheet" href="{%static '/css/styles.css' %}">
<link rel="stylesheet" href="{%static  '/css/styles_index.css' %}">
<link rel="stylesheet" href="{%static  '/css/estilo_inicio_cliente.css' %}">

<header class="container-fluid bg-dark position-sticky top-0">






  <div id="logo_rotiseria"><a class="navbar-logo" href="/">
      <img class="img-fluid " id="logo_rotiseria" src="{%static  '/img/logoblanco.png'%}" width="50%" heigth="50%"
        alt="logo">
    </a></div>




  <ul class="nav nav-pills mb-3 py-3 container" id="pills-tab" role="tablist">









    <li class="nav-item" role="presentation">

      <a class="nav-link" href="#titulo_info"><i class="bi bi-info-circle-fill"></i> Quiénes Somos </a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" href="#contacto"><i class="bi bi-chat-fill"></i> Contacto</a>


    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" href="{% url 'pedido:Menu_pagina_principal' %}"><i class="bi bi-door-closed-fill"></i>
        Menú</a>



    </li>


    {% comment %} <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Servicio De Viandas
      </a>
      <ul class="dropdown-menu" style="background-color: rgb(167, 167, 167) ;">
        <li><a class="dropdown-item" href="{% url 'pedido:listar_viandas' %}">Solicitar Vianda</a></li>

      </ul>
    </li> {% endcomment %}



    </li>



  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-inicio-tab">
    </div>




  </div>

  <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab"></div>
  </div>
  <div class="tab-pane fade " id="pills-menu" role="tabpanel" aria-labelledby="pills-menu-tab">




  </div>




  <div class="contenedor">


</header>


{%endblock %}




{% block content %}


<section>

  <div>
    <h2 id="novedades">Novedades</h2>
  </div>

  <div id="carousel1">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
          aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
          aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
          aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img
            src="https://images.pexels.com/photos/8402682/pexels-photo-8402682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
            class="img-fluid" alt="...">
        </div>
        <div class="carousel-item">
          <img
            src="https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
            class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img
            src="https://images.pexels.com/photos/11975902/pexels-photo-11975902.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
            alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Siguiente</span>
      </button>
    </div>






  </div>




</section>






<section class="contenedor_info">



  <div>
    <h2 id="titulo_info">Quiénes somos</h2>
  </div>

  <div class="texto_info"><span> <b> El Mejor Sabor </b> es una empresa familiar destacándose en el rubro
      gastronómico por la elaboración de comidas caseras. Tiene como prioridad fundamental la calidad y el
      control permanente de sus productos, la atención personalizada y los bajos precios.

      <br>
      Nuestros platos se elaboran al momento de ser solicitados, lo que garantiza calidad y sabores
      inigualables


      <br> <br>
      Tómate tu tiempo para mirar nuestro Menu en línea interactivo y pide cuando estés listo. Nos tomamos
      aproximadamente unos minuto en confirmar tu pedido y darte un tiempo estimado para que esté listo.



    </span>


  </div>


</section>


<section id="contacto">
  <h2>NUESTROS DATOS</h2>

  <div class="texto_contacto">

    <div class="direccion"><Strong> </Strong>Dirección: Sarmiento 683, San Fernando del Valle de Catamarca Argentina
    </div>
    <br>
    <div><strong> Teléfonos: </strong> 54 383 442-6185</div>
    <br>

    <div><strong> Celular: </strong>54 383 465-3630</div>
    <br>

    <div><strong> Email:</strong> Elmejorsabor@gmail.com</div>
    <br>

    <div><strong> Horario De Atencion: </strong> Lu. a Sab. de 10 a 15 y de 18 a 22 hs</div>


  </div>


</section>


{% if messages %}
{% for message in messages %}
<script>
  alert("{{message}}");
</script>
{% endfor %}
{% endif %}
{% endblock %}

templates/base/index_admin.html
{% extends 'base/base.html' %} {% load static %}


{% if messages %}
{% for message in messages %}
<script>
    alert("{{message}}");
</script>
{% endfor %}
{% endif %}


{% block title%}Inicio Administrador{%endblock %}


{% block header%}

<h1 class="titulo_pagina">Gestion De Personal</h1>
<div id="imagen_admin"> <img src="{%static  '/img/admin.png'%}" alt="admin"> </div>


{%endblock %}


{% block content %}


{%endblock %}

templates/base/menu_rotiseria.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="rotiseria" />

    <title>Menu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



    <link rel="stylesheet" href="{%static '/css/styles.css' %}">
    <link rel="stylesheet" href="{%static  '/css/styles_index.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />


    <script src="{% static 'js/scripts.js' %}"></script>





    <style>
        .nav-link,
        .usuario {
            color: #0D6EFD !important;
        }
    </style>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light  sticky-top" style="background-color: #212529 ;">
        <div class="container px-2 px-lg-2">

            <a class="navbar-logo" href="/">
                <img class="img-fluid " id="logo_rotiseria" src="{%static  '/img/logoblanco.png'%}" width="50%"
                    heigth="50%" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'pedido:Menu_pagina_principal' %}"></span>
                            Menu
                        </a>
                    </li>

                    <div class="dropdown show">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menues Disponibles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            {% for tipo_menu in tipo_de_menues %}
                            <a class="dropdown-item"
                                href="{% url 'pedido:menuxCategoria' tipo_menu.id %}">{{tipo_menu.nombre}}</a>
                            {% endfor %}
                        </div>
                    </div>






                    {% if user.is_authenticated  and user.is_superuser%}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pedido:tipo_plato' %}">
                            Listado Platos
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pedido:tipo_menu' %}">
                            Listado Tipo Menu
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pedido:listarMenues' %}">
                            Menues
                        </a>
                    </li>






                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/inicio_admin">
                            Personas
                        </a>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            Pedidos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% comment %} <a class="dropdown-item" href="#">Registrar pedido</a> {% endcomment %}
                            <a class="dropdown-item" href="{% url 'pedido:estadisticas' %}">Estadisticas</a>
                            <a class="dropdown-item" href="{% url 'pedido:todos_los_pedido_lista' %}">Estado de
                                pedidos</a>

                        </div>
                    </li>


                    {% else %}
                    {% if user.is_authenticated%}

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'pedido:listar_pedidos_clientes' %}"></span>
                                Mis Pedidos
                            </a>
                        </li>
                    {% endif %}
                    {% endif %}

                </ul>



                <ul class="navbar-nav d-flex ml-auto mb-2 mb-lg-0 ms-lg-4">
                    {% if user.is_authenticated %}
                    {% load humanize %}
                    <div class="d-flex">
                        <a href="{% url 'pedido:viewcart' %}" class="btn btn-outline-dark">
                            <i class="bi-cart-fill me-1"></i>
                            <span class="badge bg-dark text-white ms-1 rounded-pill">$.
                                {{ importe_total_carro | intcomma }}</span>
                        </a>
                    </div>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <div class="boton_login"> <span class="usuario  btn btn-ligth"> @{{ user.username }}&nbsp;&nbsp;<a
                                href="{% url 'usuario:logout' %}"><i class="bi bi-door-open-fill"></i> Cerrar Sesión</a>
                        </span></div>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'usuario:login' %}">
                            Ingresar
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'usuario:registro' %}">
                            Registrar
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <section class="container">
        {% block content%} {% endblock %}
    </section>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</body>
{% if messages %}
{% for message in messages %}
<script>
    alert("{{message}}");
</script>
{% endfor %}
{% endif %}

</html>