apps/pedido/urls.py
from django.urls import path

from .views import ListarMenuesSolicitados, Pedido, PedidoAdmin, PedidoCliente, addTipo_Plato, agregar_Menu_detalle, agregar_Menu_procesar_compra, cambiarEstadoPedidoyComentar, deleteTipo_plato, listTipo_Menu, listTipo_Plato, listar_pedidos_clientes, listar_pedidos_por_fecha, \
    modificarTipo_Plato, Menu_pagina_principal, \
     \
    detalleMenu, addMenu, menuxCategoria, editarMenu, deleteMenu, listarMenues, addTipo_Menu, \
    modificarTipo_Menu, deleteTipo_Menu, registroPedido, todos_los_pedido_lista, viewcart, agregar_Menu, eliminar_Menu, restar_Menu, cleancart, procesar_compra, estadisticas, asignarRepartidor

app_name = 'pedido'

urlpatterns = [

    path('menu/', Menu_pagina_principal, name='Menu_pagina_principal'),
    path('agregar_Menu_procesar_compra/<producto_id>',
         agregar_Menu_procesar_compra, name="agregar_Menu_procesar_compra"),

    path('tipo_menu/', listTipo_Menu, name='tipo_menu'),

    path('tipo_plato/', listTipo_Plato, name='tipo_plato'),

    path('addTipo_Plato/', addTipo_Plato, name='addTipo_Plato'),

    path('modificarTipo_Plato/<id>', modificarTipo_Plato,
         name='modificarTipo_Plato'),

    path('deleteTipo_plato/<id>', deleteTipo_plato, name='deleteTipo_plato'),

    path('addTipo_Menu/', addTipo_Menu, name='addTipo_Menu'),

    path('modificarTipo_Menu/<id>', modificarTipo_Menu, name='modificarTipo_Menu'),

    path('deleteTipo_Menu/<id>', deleteTipo_Menu, name='deleteTipo_Menu'),

    path('detalle/', detalleMenu, name='detalle'),

    path('addMenu/', addMenu, name='addMenu'),

    path('menuxCategoria/<id>/', menuxCategoria, name='menuxCategoria'),

    path('editarMenu/<id>/', editarMenu, name='editarMenu'),

    path('deleteMenu/<id>/', deleteMenu, name='deleteMenu'),

    path('listarMenues/', listarMenues, name='listarMenues'),


    path('viewcart/', viewcart, name="viewcart"),

    path('agregar_Menu/<producto_id>', agregar_Menu, name="agregar_Menu"),


    path('delcart/<producto_id>', eliminar_Menu, name="delcart"),

    path('restarcart/<producto_id>', restar_Menu, name="restarcart"),

    path('cleancart/', cleancart, name="cleancart"),

    path('procesar_compra/', procesar_compra, name="procesar_compra"),

    path('registroPedido/', registroPedido, name="registroPedido"),
    path('pedidoCliente/', PedidoCliente, name="pedidoCliente"),



    path('PedidoAdmin/', PedidoAdmin, name="PedidoAdmin"),


    path('listar_pedidos_clientes/', listar_pedidos_clientes,
         name="listar_pedidos_clientes"),

    path('todos_los_pedido_lista/', todos_los_pedido_lista,
         name="todos_los_pedido_lista"),





    path('cambiarEstadoPedidoyComentar/<int:pedido_id>',
         cambiarEstadoPedidoyComentar, name="cambiarEstadoPedidoyComentar"),

    path('estadisticas/', estadisticas, name="estadisticas"),

    path('listar_pedidos_por_fecha', listar_pedidos_por_fecha,
         name="listar_pedidos_por_fecha"),

    path('ListarMenuesSolicitados', ListarMenuesSolicitados,
         name="ListarMenuesSolicitados"),



    path('asignarRepartidor/<id>', asignarRepartidor, name='asignarRepartidor'),




]

rotiseriaelmejorsabor/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/index.html'), name='inicio'),
    path('inicio_admin/', TemplateView.as_view(template_name='base/index_admin.html'),
         name='inicio_admin'),
    path('persona/', include('apps.persona.urls', namespace='persona')),
    path('persona/cliente', include('apps.persona.urls', namespace='cliente')),
    path('persona/empleado', include('apps.persona.urls', namespace='empleado')),


    path('menu/', include('apps.pedido.urls', namespace='menu')),
    path('menu/compra/', include('apps.pedido.urls', namespace='compra')),
    path('pedido/', include('apps.pedido.urls', namespace='pedido')),

    path('usuario/', include('apps.usuario.urls', namespace='usuario')),

    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pedido/models.py
from datetime import date
from distutils.command.upload import upload
from django.db import models
from model_utils import Choices
from apps.persona.models import Cliente
from django.contrib.auth.models import User


class Tipo_Plato(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = "Tipo De Plato"
        verbose_name = 'Tipo De Plato'
        verbose_name_plural = 'Tipos De Platos'
        ordering = ['id']


class Tipo_Menu(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = "Tipo De Menu"
        verbose_name = 'Tipo De Menu'
        verbose_name_plural = 'Tipos De Menues'
        ordering = ['id']


class Menu(models.Model):
    nombre = models.CharField(max_length=30)
    imagen = models.ImageField(upload_to='images/', blank=True)
    descripcion = models.CharField(max_length=500, blank=True)
    precio = models.IntegerField()
    tipo_menu = models.ForeignKey(Tipo_Menu, on_delete=models.PROTECT)
    tipo_plato = models.ForeignKey(Tipo_Plato, on_delete=models.PROTECT)

    vigente = models.BooleanField(default=True)

    def __str__(self):
        return "%s %s %s %s " % (self.nombre, self.precio, self.tipo_menu, self.tipo_plato)


class Pedido(models.Model):

    cliente = models.ForeignKey(
        "persona.Cliente", on_delete=models.CASCADE, null=False)

    fechaPedido = models.DateField()
    horaEntrega = models.TimeField(blank=True)
    TipoEntrega = models.ForeignKey(
        "TipoEntrega", on_delete=models.CASCADE, null=True)
    Estado = models.ForeignKey(
        "Estado", on_delete=models.CASCADE, null=True, blank=True)
    menu = models.ManyToManyField(Menu, blank=True)
    repartidor = models.ForeignKey(
        "persona.Repartidor", on_delete=models.CASCADE, null=True, blank=True)

    comentario = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.cliente.nombre + ' ' + self.cliente.apellido + '-' + self.Estado.estadoPedido + '-' + self.TipoEntrega.tipoEntrega


class Estado(models.Model):
    ESTADO_PEDIDO = Choices("Pendiente", "En preparación",
                            "En camino", "Entregado", "Devuelto", "Cancelado")
    PENDIENTE = "Pendiente"
    estadoPedido = models.CharField(
        max_length=15, choices=ESTADO_PEDIDO, default=PENDIENTE, unique=True)

    def __str__(self):
        return self.estadoPedido


class TipoEntrega(models.Model):
    TIPO_ENTREGA = Choices("Delivery", "Retiro")
    tipoEntrega = models.CharField(
        max_length=8, choices=TIPO_ENTREGA, default="Retiro", unique=True)

    def __str__(self):
        return self.tipoEntrega

apps/pedido/views.py
import datetime
from operator import itemgetter
from django.http import Http404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, permission_required
from .forms import DateRangeForm, DateRangeCadeteForm
from apps.pedido.carro import Carro
from apps.persona.models import Repartidor
from .forms import ActualizarPedidoForm, PedidoClienteForm, PedidoForm, nuevoMenuForm, nuevoTipoMenuForm, nuevoTipoPlatoForm
from .models import Pedido, Estado, Menu, Tipo_Plato, Tipo_Menu
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator


def compra(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/compra.html')


def estadisticas(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/estadisticas.html')


def estado_pedido(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/estado_pedido.html')


def orden_compra(request):
    return render(request, 'pedido/orden_compra.html')


def pedidos_vista_admin(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/pedidos_vista_admin.html')


def menu(request):
    return render(request, 'pedido/menu.html')


####################################################################################


def listar_menu(request):
    return render(request, 'pedido/listar_menu.html', {'menus': Menu.objects.all()})


def gestion_menu(request):
    if request.user.is_authenticated and request.user.is_staff:
        if (request.method == "POST"):
            menu = nuevoMenuForm(request.POST)

            for field in menu:
                print("Field Error:", field.name, field.errors)

            if (menu.is_valid()):
                nuevo_menu = menu.save()
                nuevo_menu.save()

                messages.success(request, 'Se ha agregado correctamente el menu {}'.format(
                    nuevo_menu))
                return redirect('pedido:gestion_menu')

        else:
            menu = nuevoMenuForm()

        return render(request, 'pedido/gestion_menu.html', {'menu': menu})


def eliminar_menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        menu = get_object_or_404(Menu, id=id)
        menu.delete()
        return redirect(to='pedido:listar_menu')


def modificar_menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        menu = get_object_or_404(Menu, id=id)
        data = {
            'menu': nuevoMenuForm(instance=menu)
        }
        if (request.method == "POST"):

            formulario = nuevoMenuForm(

                data=request.POST, instance=menu, files=request.FILES)

            if formulario.is_valid():
                formulario.save()
                data["mensaje"] = "Modificacion correcta"

                return redirect(to="pedido:listar_menu")

            data["menu"] = formulario

        return render(request, 'pedido/modificar_menu.html', data)


##########################################################################################


def gestion_plato(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/gestion_plato.html')


def gestion_ingrediente(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'pedido/gestion_Ingrediente.html')


############################################################################################




def Menu_pagina_principal(request):
    busqueda = request.POST.get("buscador")
    product_list = Menu.objects.order_by('nombre')
    page = request.GET.get('page', 1)

    if busqueda:
        product_list = Menu.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    try:
        paginator = Paginator(product_list, 12)
        product_list = paginator.page(page)
    except:
        raise Http404

    data = {'entity': product_list,
            'paginator': paginator
            }
    return render(request, 'pedido/menuDeComidas.html', data)



def menuxCategoria(request, id):
    busqueda = request.POST.get("buscador")
    lista_productos = Menu.objects.filter(tipo_menu=id)

    if busqueda:
        lista_productos = Menu.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    data = {'entity': lista_productos}
    return render(request, 'pedido/menuDeComidas.html', data)


def detalleMenu(request, id):
    menu = get_object_or_404(Menu, id=id)
    otrosProductos = Menu.objects.filter(tipo_menu=menu.tipo_menu)
    data = {
        'menu': menu,
        'productosRelacionados': otrosProductos
    }
    return render(request, 'pedido/menu/detalle.html', data)


@login_required(login_url='/login')
def addMenu(request):
    data = {
        'form': nuevoMenuForm()
    }

    if request.method == 'POST':
        formulario = nuevoMenuForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="pedido:listarMenues")
        else:
            data["form"] = formulario
    return render(request, 'pedido/menu/agregar.html', data)


def listarMenues(request):
    if request.user.is_authenticated and request.user.is_staff:
        busqueda = request.POST.get("buscador")
        lista_productos = Menu.objects.order_by('nombre')
        page = request.GET.get('page', 1)
        if busqueda:
            lista_productos = Menu.objects.filter(
                Q(nombre__icontains=busqueda) |
                Q(descripcion__icontains=busqueda)
            ).distinct()

        try:
            paginator = Paginator(lista_productos, 6)
            lista_productos = paginator.page(page)
        except:
            raise Http404

        data = {'entity': lista_productos,
                'title': 'LISTADO DE MENUES',
                'paginator': paginator
                }
        return render(request, 'pedido/menu/listar.html', data)


def editarMenu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        menu = get_object_or_404(Menu, id=id)
        data = {
            'form': nuevoMenuForm(instance=menu)
        }

        if request.method == 'POST':
            formulario = nuevoMenuForm(
                data=request.POST, instance=menu, files=request.FILES)
            if formulario.is_valid():
                formulario.save()
                messages.success(request, "Registro modificado correctamente")
                return redirect(to="pedido:listarMenues")
            data["form"] = formulario
        return render(request, 'pedido/menu/modificar.html', data)


def deleteMenu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        producto = get_object_or_404(Menu, id=id)
        producto.delete()
        messages.success(request, "Registro eliminado correctamente")
        return redirect(to="pedido:listarMenues")

@permission_required('pedido.view_Tipo_Menu', login_url="usuario:login")
def listTipo_Menu(request):
    lista_categorias = Tipo_Menu.objects.all().order_by('nombre')
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(lista_categorias, 6)
        lista_categorias = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_categorias,
            'title': 'Tipo De Menu',
            'paginator': paginator
            }

    return render(request, 'pedido/tipo_menu.html', data)

@permission_required('pedido.add_Tipo_Menu', login_url="usuario:login")
def addTipo_Menu(request):
    if request.user.is_authenticated and request.user.is_staff:
        data = {
            'form': nuevoTipoMenuForm()
        }
        if request.method == 'POST':
            formulario = nuevoTipoMenuForm(data=request.POST)

            if formulario.is_valid():
                formulario.save()
                messages.success(request, "Registro agregado correctamente")
                return redirect(to="pedido:tipo_menu")
            else:
                data["form"] = formulario
        return render(request, 'pedido/tipo_menu/agregar_tipo_menu.html', data)

@permission_required('pedido.change_Tipo_Menu', login_url="usuario:login")
def modificarTipo_Menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        tipo_menu = get_object_or_404(Tipo_Menu, id=id)

        data = {
            'form': nuevoTipoMenuForm(instance=tipo_menu)
        }
        if request.method == 'POST':
            formulario = nuevoTipoMenuForm(
                data=request.POST, instance=tipo_menu)
            if formulario.is_valid():
                formulario.save()
                messages.success(request, "Registro modificado correctamente")
                return redirect(to="pedido:tipo_menu")
            else:
                data["form"] = formulario

        return render(request, 'pedido/tipo_menu/modificar_tipo_menu.html', data)

@permission_required('pedido.delete_Tipo_Menu', login_url="usuario:login")
def deleteTipo_Menu(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        categoria = get_object_or_404(Tipo_Menu, id=id)
        categoria.delete()
        messages.success(request, "Registro eliminado correctamente")
        return redirect(to="pedido:tipo_menu")


def listTipo_Plato(request):
    if request.user.is_authenticated and request.user.is_staff:

apps/pedido/templates/pedido/Tipo_menu.html
{% extends 'base/menu_rotiseria.html ' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body  table-responsive">
                        <div class="d-flex justify-content-end mb-2 mx-2">


                            <a href="{% url 'pedido:addTipo_Menu' %}" class="btn btn-dark btn-sm pull-right"
                                type="submit">
                                Nuevo Tipo De Menu

                            </a>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for tipo_menu in entity %}
                                <tr>
                                    <td>{{tipo_menu.id }}</td>
                                    <td>{{tipo_menu.nombre }}</td>

                                    <td colspan="2" class="text-center">
                                        <a class="btn btn-secondary btn-sm"
                                            href="{% url 'pedido:modificarTipo_Menu' tipo_menu.id %}" type="button"><i
                                                class="bi bi-pencil-square"></i></a>
                                        <a class="btn btn-danger btn-sm"
                                            href="{% url 'pedido:deleteTipo_Menu' tipo_menu.id %}" type="button"><i
                                                class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No se encontraron Tipos De Menus!!</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'pedido/paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/pedido/templates/pedido/designar_cadete.html
{% extends 'base/menu_rotiseria.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Asignar Repartidor
{% endblock %}


{% block head %}

{% endblock %}
{% block content %}

<fieldset>
    <legend class="leyenda"> Editar Datos</legend>
    <section>

        <form action="{% url 'pedido:asignarRepartidor' id %}" method="post" enctype="multipart/form-data" class="formulario">
            {% csrf_token %}


<!-- 
            <label for="{{form.repartidor.id_for_label}}">Repartidor: </label>
            {{form}} -->


            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="mb-3">
                        {% if field.error %}
                        <span class="textoForm">
                            {{ field.errors }}
                        </span>
                        {% endif %}


                        <!-- <label for="{{form.cliente.id_for_label}}">Cliente: </label>
                        {{form.cliente}}


                        <label for="{{form.fechaPedido.id_for_label}}">Fecha De Pedido: </label>
                        {{form.fechaPedido}}




                        <label for="{{form.horaEntrega.id_for_label}}">Hora De Entrega Del Pedido: </label>
                        {{form.horaEntrega}}


                        <label for="{{form.TipoEntrega.id_for_label}}">Tipo De Entrega: </label>
                        {{form.TipoEntrega}}



                        <label for="{{form.repartidor.id_for_label}}">Repartidor: </label>
                        {{form.repartidor}} -->
                            {{form | crispy}}

                            <br>

                        <button class="btn btn-primary btn-lg" id="submitButton" type="submit">Designar</button>
                        <a class="btn btn-danger btn-lg" href="{% url 'pedido:todos_los_pedido_lista'%}">Volver</a>
            





                    </div>
                </div>
                <div class="col-3"></div>
            </div>

        

            <div>
                <br>


                
             
                


        </form>
    </section>
</fieldset>



{% endblock %}

apps/pedido/templates/pedido/estadoPedidosClientes.html
{% extends 'base/menu_rotiseria.html' %}

{% load static %}

{% block title %}
Estado de pedidos
{% endblock %}
{% block head %}



{% endblock %}
{% block content %}
<div>
    <div class="image-aboutus-banner fondo">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">
                        <h1 class="lg-text titulos">
                            {% if user.is_staff %}
                            Listado de pedidos
                            {% else %}
                            Mis pedidos
                            {% endif %}
                        </h1>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="paddingTB60"
        style="background-image: url({% static 'img/form-difuminado.png' %});background-repeat: no-repeat;background-size: cover;background-position:center;overflow: hidden;">
        <div class="container" id="listaPedidos">
            {% for pedido in pedidos %}
            <ul class="list-group list-group-horizontal">
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-60 justify-content-between">
                        <h5 class="mb-1">{{pedido.cliente.nombre}} {{pedido.cliente.apellido}}</h5>
                        <small class="text-muted">{{pedido.fechaPedido}}</small>

                    </div>
                    <div class="d-flex w-60 justify-content-between">
                        <p class="mb-1">
                            {% if pedido.menu.all.count == 1 %}


                            {% for plato in pedido.menu.all %}
                            {{plato.nombre}}
                            {% endfor %}
                            {% else %}
                            {% for plato in pedido.menu.all %}
                            {{plato.nombre}},
                            {% endfor %}
                            {% endif %}
                        </p>
                        <small class="text-muted">Tiempo de entrega estimado</small>
                    </div>
                    <div class="d-flex w-60 justify-content-between">
                        <small class="text-muted">{{pedido.TipoEntrega.tipoEntrega}}</small>
                        <small class="text-muted">{{pedido.horaEntrega}}</small>
                    </div>
                </a>
                <li class="list-group-item">
                    {% if user.is_staff %}
                    <form method="post" action="{% url 'pedido:cambiarEstadoPedidoyComentar' pedido.id %}">
                        <div class="text-center">
                            {% csrf_token %}
                            <select name="estadoPedido" class="selectpicker form-select">
                                {% for valor,texto in form.fields.estadoPedido.choices %}
                                {% if valor == pedido.Estado.id %}
                                <option value="{{valor}}" selected>{{texto}}</option>
                                {% else %}
                                <option value="{{valor}}">{{texto}}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                            {% if pedido.comentario is None %}
                            <input type="text" name="comentario" maxlength="500" required value="" id="id_comentario">
                            {% else %}
                            <input type="text" name="comentario" maxlength="500" required value="{{pedido.comentario}}"
                                id="id_comentario">
                            {% endif %}


                            <button type="submit" class="btn btn-primary pl-2" id="guardarEstadoPedido">Guardar</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="text-center">
                        {% csrf_token %}
                        <select name="estadoPedido" class="selectpicker form-select" disabled>
                            {% for valor,texto in form.fields.estadoPedido.choices %}
                            {% if valor == pedido.Estado.id %}
                            <option value="{{valor}}" selected>{{texto}}</option>
                            {% else %}
                            <option value="{{valor}}">{{texto}}</option>
                            {% endif %}
                            {% endfor %}




                        </select>
                        {% endif %}




                        {% comment %} INPUT QUE MUESTRE EL CADETE Y UN BOTON QUE LLEVE A OTRA PAGINA COMO EL MODIFICAR
                        PERO QUE SOLO SE CAMBIE EL APARTADO CADETE DEL PEDIDO {% endcomment %}



                        <label class="textoForm" for="repartidor_nombre">Repartidor</label>

                        <input type="text" name="repartidor_nombre" class="form-control" required id="repartidor_nombre"
                            value="{{pedido.repartidor}} " disabled>

                            {% if user.is_authenticated  and user.is_superuser%}
                        <a class="btn btn-warning btn-sm " id="submitButton" type="submit"
                            href=" {% url 'pedido:asignarRepartidor' pedido.id %}">Designar Repartidor</a>

                            {% endif%}






            </ul>
            {% endfor %}
        </div>
    </div>
</div>

{% comment %} <script src="{% static 'js/estadoPedidos.js' %}" type="text/javascript"></script> {% endcomment %}
{% endblock %}-

apps/pedido/templates/pedido/modificar_menu.html
{% extends 'base/base.html' %} {% load static %}


{% block title%}Editar Menu{%endblock %}



{% block header%}

<h1 class="titulo_pagina">Editar menu</h1>

<div id="imagen_menu"> <img src="{%static  '/img/menu.png'%}" alt="Foto menu generico"> </div>

{%endblock %}

{% block content%}




<fieldset>

    <legend class="leyenda"> Datos Del Menu</legend>

    <form class="row " action="#" method="POST" id="formulario">


        {% csrf_token %}

        {{menu.as_p }}

        <div>
            <button type="submit" class="btn btn-success">Guardar</button>
            <button type="reset" class="btn btn-danger">Cancelar</button>
        </div>
        < </form> </fieldset> {% endblock %}

apps/pedido/templates/pedido/tipo_plato.html
{% extends 'base/menu_rotiseria.html ' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body  table-responsive">
                        <div class="d-flex justify-content-end mb-2 mx-2">


                            <a href="{% url 'pedido:addTipo_Plato' %}" class="btn btn-dark btn-sm pull-right"
                                type="submit">
                                Nuevo Tipo De Plato
                            </a>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for tipo_plato in entity %}
                                <tr>
                                    <td>{{tipo_plato.id }}</td>
                                    <td>{{tipo_plato.nombre }}</td>
                                    <td colspan="2" class="text-center">
                                        <a class="btn btn-secondary btn-sm"
                                            href="{% url 'pedido:modificarTipo_Plato' tipo_plato.id %}" type="button"><i
                                                class="bi bi-pencil-square"></i></a>
                                        <a class="btn btn-danger btn-sm"
                                            href="{% url 'pedido:deleteTipo_plato' tipo_plato.id %}" type="button"><i
                                                class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No se encontraron Tipos De Platos!!</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'pedido/paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}