apps/persona/urls.py
from django.urls import path

from . import views
from .views import creacion_cliente, listar_clientes, modificar_cliente, creacion_empleado, listar_empleados, eliminar_cliente, modificar_empleado, eliminar_empleado, listar_repartidores, modificar_repartidor, eliminar_repartidor

app_name = 'persona'

urlpatterns = [
    path('registrar_cliente/', creacion_cliente, name='registrar_cliente'),

    path('listar_clientes/', listar_clientes, name='listar_clientes'),

    path('modificar_cliente/<id>', modificar_cliente, name='modificar_cliente'),

    path('registrar_empleado/', views.creacion_empleado, name='registrar_empleado'),

    path('creacion_repartidor/', views.creacion_repartidor,
         name='creacion_repartidor'),

    path('listar_empleados/', listar_empleados, name='listar_empleados'),

    path('modificar_empleado/<id>', modificar_empleado, name='modificar_empleado'),


    path('eliminar_cliente/<id>', eliminar_cliente, name='eliminar_cliente'),

    path('eliminar_empleado/<id>', eliminar_empleado, name='eliminar_empleado'),



    ####################


    path('listar_repartidores/', listar_repartidores, name='listar_repartidores'),

    path('modificar_repartidor/<id>', modificar_repartidor,
         name='modificar_repartidor'),


    path('eliminar_repartidor/<id>', eliminar_repartidor,
         name='eliminar_repartidor'),



    ###############


]

rotiseriaelmejorsabor/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/index.html'), name='inicio'),
    path('inicio_admin/', TemplateView.as_view(template_name='base/index_admin.html'),
         name='inicio_admin'),
    path('persona/', include('apps.persona.urls', namespace='persona')),
    path('persona/cliente', include('apps.persona.urls', namespace='cliente')),
    path('persona/empleado', include('apps.persona.urls', namespace='empleado')),


    path('menu/', include('apps.pedido.urls', namespace='menu')),
    path('menu/compra/', include('apps.pedido.urls', namespace='compra')),
    path('pedido/', include('apps.pedido.urls', namespace='pedido')),

    path('usuario/', include('apps.usuario.urls', namespace='usuario')),

    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/persona/models.py
from datetime import datetime
from django.db import models
from enum import unique

from django.forms import ValidationError


# Create your models here.


class Persona(models.Model):
    CUIT = models.CharField(max_length=11, unique=True)
    apellido = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    celular = models.DecimalField(
        blank=True, null=True, max_digits=78, decimal_places=0)
    telefono_fijo = models.DecimalField(
        blank=True, null=True, max_digits=78, decimal_places=0)
    fecha_nacimiento = models.DateField()
    calle = models.CharField(max_length=30)
    numero = models.IntegerField()
    localidad = models.CharField(max_length=30)
    departamento = models.CharField(max_length=30)
    observaciones = models.TextField(max_length=1000, blank=True)
    estado = models.BooleanField(default=True)

    class Meta:
        abstract = True

    def validar_fecha_nacimiento(self):
        fecha_actual = datetime.now.strftime("%Y-%m-%d")
        if (self.fecha_nacimiento.strftime("%Y-%m-%d") > fecha_actual):
            raise ValidationError(
                'La fecha de nacimiento es mayor a la actual')


class Cliente(Persona):

    def __str__(self):
        return "%s %s %s %s" % (self.CUIT, self.apellido, self.nombre, self.calle)


class Empleado(Persona):
    EMPLEADO = 'E'

    fecha_ingreso_trabajar = models.DateField()

    def __str__(self):
        return "%s %s %s %s" % (self.CUIT, self.apellido, self.nombre)


class Repartidor(Persona):
    NORTE = 'N'
    SUR = 'S'
    ESTE = 'E'
    OESTE = 'O'

    ZONA = [
        (NORTE, 'NORTE'),
        (SUR, 'SUR'),
        (ESTE, 'ESTE'),
        (OESTE, 'OESTE')
    ]
    fecha_ingreso_trabajar = models.DateField()
    vigencia_carnet = models.DateField()
    patente = models.CharField(max_length=30)
    zona = models.CharField(max_length=1, choices=ZONA)

    def __str__(self):
        return " %s %s  %s" % ( self.apellido, self.nombre, self.patente)

apps/persona/forms.py
from django import forms
from django.forms import DateInput
from .models import Cliente, Empleado, Repartidor


class nuevoClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente

        fields = (
            "CUIT", "apellido", "nombre", "celular", "telefono_fijo", "fecha_nacimiento", "calle", "numero",
            "localidad",
            "departamento", "observaciones")

        widgets = {

            'fecha_nacimiento': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),

        }


class nuevoEmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado

        fields = (
            "CUIT", "apellido", "nombre", "celular", "telefono_fijo", "fecha_nacimiento", "calle", "numero",
            "localidad", "departamento", "observaciones", "fecha_ingreso_trabajar"
        )

        widgets = {

            'fecha_nacimiento': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),

            'fecha_ingreso_trabajar': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),

        }


class nuevoRepartidorForm(forms.ModelForm):
    class Meta:
        model = Repartidor

        fields = (
            "CUIT", "apellido", "nombre", "celular", "telefono_fijo", "fecha_nacimiento", "calle", "numero",
            "localidad", "departamento", "observaciones", "fecha_ingreso_trabajar", "vigencia_carnet",
            "patente", "zona"
        )

        widgets = {

            'fecha_nacimiento': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),

            'fecha_ingreso_trabajar': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),

            'vigencia_carnet': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),

        }

apps/persona/views.py
from audioop import reverse

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from .forms import nuevoClienteForm, nuevoEmpleadoForm, nuevoRepartidorForm
from .models import Cliente, Empleado, Repartidor
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.

############################## CLIENTE##############################

@permission_required('persona.view_Cliente', login_url="usuario:login")
def listar_clientes(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'persona/listar_clientes.html', {'clientes': Cliente.objects.all()})

@permission_required('persona.add_Cliente', login_url="usuario:login")
def creacion_cliente(request):
    if request.user.is_authenticated and request.user.is_staff:
        if (request.method == "POST"):
            cliente = nuevoClienteForm(request.POST)
            if (cliente.is_valid()):
                nuevo_cliente = cliente.save()
                nuevo_cliente.save()

                messages.success(request, 'Se ha agregado correctamente el Cliente {}'.format(
                    nuevo_cliente))
                return redirect('persona:registrar_cliente')
        else:
            cliente = nuevoClienteForm()

        return render(request, 'persona/cliente.html', {'form': cliente})



@permission_required('persona.change_Cliente', login_url="usuario:login")
def modificar_cliente(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        cliente = get_object_or_404(Cliente, id=id)
        data = {
            'form': nuevoClienteForm(instance=cliente)
        }
        if (request.method == "POST"):

            formulario = nuevoClienteForm(
                data=request.POST, instance=cliente, files=request.FILES)

            if formulario.is_valid():
                formulario.save()
                data["mensaje"] = "Modificacion correcta"

                return redirect(to="persona:listar_clientes")

            data["form"] = formulario

        return render(request, 'persona/modificar_cliente.html', data)

@permission_required('persona.delete_Cliente', login_url="usuario:login")
def eliminar_cliente(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        cliente = get_object_or_404(Cliente, id=id)
        cliente.delete()
        return redirect(to='persona:listar_clientes')


############################## EMPLEADO##############################

@permission_required('persona.view_Empleado', login_url="usuario:login")
def listar_empleados(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'persona/listar_empleados.html', {'empleados': Empleado.objects.all()})


@permission_required('persona.add_Empleado', login_url="usuario:login")
def creacion_empleado(request):
    if request.user.is_authenticated and request.user.is_staff:
        if (request.method == "POST"):
            empleado = nuevoEmpleadoForm(request.POST)

            if (empleado.is_valid()):
                nuevo_empleado = empleado.save()

                nuevo_empleado.save()

                messages.success(
                    request, 'se ha creado el Empleado exitosamente')

                return redirect(to="persona:registrar_empleado")

        else:
            empleado = nuevoEmpleadoForm()

        return render(request, 'persona/empleado.html', {'empleado': empleado})


@permission_required('persona.delete_Empleado', login_url="usuario:login")
def eliminar_empleado(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        empleado = get_object_or_404(Empleado, id=id)
        empleado.delete()
        return redirect(to='persona:listar_empleados')


@permission_required('persona.change_Empleado', login_url="usuario:login")
def modificar_empleado(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        empleado = get_object_or_404(Empleado, id=id)
        data = {
            'empleado': nuevoEmpleadoForm(instance=empleado)
        }
        if (request.method == "POST"):

            formulario = nuevoEmpleadoForm(

                data=request.POST, instance=empleado, files=request.FILES)

            if formulario.is_valid():
                formulario.save()
                data["mensaje"] = "Modificacion correcta"

                return redirect(to="persona:listar_empleados")

            data["empleado"] = formulario

        return render(request, 'persona/modificar_empleado.html', data)


############################## CADETE##############################

@permission_required('persona.add_Repartidor', login_url="usuario:login")
def creacion_repartidor(request):
    if request.user.is_authenticated and request.user.is_staff:
        if (request.method == "POST"):
            repartidor = nuevoRepartidorForm(request.POST)
            if (repartidor.is_valid()):
                nuevo_repartidor = repartidor.save()
                nuevo_repartidor.save()

                messages.success(request, 'Se ha agregado correctamente el Repartidor {}'.format(
                    nuevo_repartidor))
                return redirect('persona:creacion_repartidor')
        else:
            repartidor = nuevoRepartidorForm()

        return render(request, 'persona/repartidor.html', {'repartidor': repartidor})

@permission_required('persona.delete_Repartidor', login_url="usuario:login")
def eliminar_repartidor(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        repartidor = get_object_or_404(Repartidor, id=id)
        repartidor.delete()
        return redirect(to='persona:listar_repartidores')

@permission_required('persona.change_Repartidor', login_url="usuario:login")
def modificar_repartidor(request, id):
    if request.user.is_authenticated and request.user.is_staff:
        repartidor = get_object_or_404(Repartidor, id=id)
        data = {
            'repartidor': nuevoRepartidorForm(instance=repartidor)
        }
        if (request.method == "POST"):

            formulario = nuevoRepartidorForm(

                data=request.POST, instance=repartidor, files=request.FILES)

            if formulario.is_valid():
                formulario.save()
                data["mensaje"] = "Modificacion correcta"

                return redirect(to="persona:listar_repartidores")

            data["repartidor"] = formulario

        return render(request, 'persona/modificar_repartidor.html', data)

@permission_required('persona.viwe_Repartidor', login_url="usuario:login")
def listar_repartidores(request):
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'persona/listar_repartidores.html', {'repartidores': Repartidor.objects.all()})

apps/persona/templates/persona/cliente.html
{% extends 'base/base.html' %} {% load static %}
{% block title%}Cliente{%endblock %}


{% block header%}<h1 class="titulo_pagina">REGISTRO DE CLIENTE</h1>



<style type="text/css">
  label {
    color: white
  }
</style>




<div id="imagen_cliente">
  <img src="{%static  '/img/imagen_cliente.png'%}" alt="Foto cliente genericas" />
</div>{% endblock %}



{% block content %}
<fieldset>
  <legend class="leyenda">Datos Cliente</legend>

  <section>

    <form action="#" method=POST class="formulario">
      {% csrf_token %}



      {{form.as_p }}








      <button type="submit" class="btn btn-success">Guardar</button>
      <button type="reset" class="btn btn-danger">Cancelar</button>

    </form>
  </section>
</fieldset>

{% endblock %}




{% if messages %}
{% for message in messages %}
<div class="row">
  <div class="alert {% if message.tags == "success" %}alert-success {% else %}alert-danger{% endif %} alert-dismissible"
    role="alert">
    <button class="close" aria-label="close" data-dismiss="alert" type="button"><span
        aria-hidden="true">x</span></button>
    <p>{{ message|safe }}</p>
  </div>
</div>
{% endfor %}
{% endif %}

apps/persona/templates/persona/empleado.html
{% extends 'base/base.html' %} {% load static %}



{% block title%}Empleado{%endblock %}






{% block header%}
<style type="text/css">
    label {
        color: white
    }
</style>

<h1 class="titulo_pagina">REGISTRO DE EMPLEADO</h1>
<div id="foto_delivery"> <img src="{%static  '/img/delivery.png'%}" alt="Imagen delivery"> </div>

{%endblock %}



{% if messages %}
{% for message in messages %}
<div class="row">
    <div class="alert {% if message.tags == "success" %}alert-success {% else %}alert-danger{% endif %} alert-dismissible"
        role="alert">
        <button class="close" aria-label="close" data-dismiss="alert" type="button"><span
                aria-hidden="true">x</span></button>
        <p>{{ message|safe }}</p>
    </div>
</div>
{% endfor %}
{% endif %}

{% block content %}



<fieldset>
    <legend class="leyenda"> Datos De Empleado</legend>
    <section>

        <form action="#" method="post" enctype="multipart/form-data" class="formulario">
            {% csrf_token %}



            {{empleado.as_p }}

            <button type="submit" class="btn btn-success">Guardar</button>
            <button type="reset" class="btn btn-danger">Cancelar</button>



        </form>
    </section>
</fieldset>
<script type="text/javascript" src="{%static 'js/rotiseria.js'%}" defer> </script>
{%endblock %}

apps/persona/templates/persona/listar_clientes.html
{% extends 'base/base.html' %} {% load static %}
{% block title%}Lista De Clientes{%endblock %}


{% block header%}<h1 class="titulo_pagina">Lista De Clientes</h1>


{% endblock %}

{% block content %}

{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %}
<div class="message" role="status">{{ message }}</div>{% endif %}
{% if message.tags == 'error' %}
<div class="errors" role="alert">{{ message }}</div>{% endif %}
{% endfor %}
{% endif %}
<div class="container">

    <div class="table-responsive-lg">
        <table class="table-dark table-hover; table table-bordered  table-sm  align-middle">
            <thead>
                <tr>
                    <th scope="col-3">CUIT</th>
                    <th scope="col-3">Apellido</th>
                    <th scope="col-4">Nombre</th>
                    <th scope="col">Celular</th>
                    <th scope="col">Telefono Fijo</th>
                    <th scope="col">Calle</th>
                    <th scope="col">Numero</th>
                    <th scope="col">Localidad</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Observaciones</th>
                    <th scope="col">opciones</th>

                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}

                <tr>
                    <td scope="row">{{cliente.CUIT}}</td>
                    <td scope="row">{{cliente.apellido}}</td>
                    <td scope="row">{{cliente.nombre}}</td>
                    <td scope="row">{{cliente.celular}}</td>
                    <td scope="row">{{cliente.telefono_fijo}}</td>
                    <td scope="row">{{cliente.calle}}</td>
                    <td scope="row">{{cliente.numero}}</td>
                    <td scope="row">{{cliente.localidad}}</td>
                    <td scope="row">{{cliente.departamento}}</td>
                    <td scope="row">{{cliente.observaciones}}</td>


                    <td scope="row">



                        <a class=" btn btn-info btn-sm" href="{% url 'persona:modificar_cliente' cliente.id  %}"><i
                                class="bi bi-pencil-square"></i></a>

                        <a class="btn btn-danger btn-sm" href="{% url 'persona:eliminar_cliente' cliente.id  %} "
                            onclick="return confirm('¿Está seguro que desea eliminar el registro?')"><i
                                class="bi bi-trash2-fill"></i></a>
                    </td>
                </tr>


                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

apps/persona/templates/persona/listar_empleados.html
{% extends 'base/base.html' %} {% load static %}
{% block title%}Lista De Clientes{%endblock %}



{% block header%}<h1 class="titulo_pagina">Lista De Empleados</h1>


{% endblock %}

{% block content %}

{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %} <div class="message" role="status">{{ message }}</div>{% endif %}
{% if message.tags == 'error' %} <div class="errors" role="alert">{{ message }}</div>{% endif %}
{% endfor %}
{% endif %}
<div class="container">

    <div class="table-responsive-lg">
        <table class="table-dark table-hover; table table-bordered  table-sm  align-middle">
            <thead>
                <tr>
                    <th scope="col-3">CUIT</th>
                    <th scope="col-3">Apellido</th>
                    <th scope="col-4">Nombre</th>
                    <th scope="col">Celular</th>
                    <th scope="col">Telefono Fijo</th>
                    <th scope="col">Calle</th>
                    <th scope="col">Numero</th>
                    <th scope="col">Localidad</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Observaciones</th>
                    <th scope="col">Fecha de ingreso</th>
                    <th scope="col">opciones</th>

                </tr>
            </thead>
            <tbody>
                {% for empleado  in empleados %}

                <tr>
                    <td scope="row">{{empleado.CUIT}}</td>
                    <td scope="row">{{empleado.apellido}}</td>
                    <td scope="row">{{empleado.nombre}}</td>
                    <td scope="row">{{empleado.celular}}</td>
                    <td scope="row">{{empleado.telefono_fijo}}</td>
                    <td scope="row">{{empleado.calle}}</td>
                    <td scope="row">{{empleado.numero}}</td>
                    <td scope="row">{{empleado.localidad}}</td>
                    <td scope="row">{{empleado.departamento}}</td>
                    <td scope="row">{{empleado.observaciones}}</td>
                    <td scope="row">{{empleado.fecha_ingreso_trabajar}}</td>
                    <td scope="row">



                        <a class=" btn btn-info btn-sm" href="{% url 'persona:modificar_empleado' empleado.id  %}"><i
                                class="bi bi-pencil-square"></i></a>

                        <a class="btn btn-danger btn-sm" href="{% url 'persona:eliminar_empleado' empleado.id  %} "
                            onclick="return confirm('¿Está seguro que desea eliminar el registro?')"><i
                                class="bi bi-trash2-fill"></i></a>
                    </td>




                </tr>


                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

apps/persona/templates/persona/listar_repartidores.html
{% extends 'base/base.html' %} {% load static %}
{% block title%}Lista De Clientes{%endblock %}



{% block header%}<h1 class="titulo_pagina">Lista De Repartidores</h1>


{% endblock %}

{% block content %}

{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %} <div class="message" role="status">{{ message }}</div>{% endif %}
{% if message.tags == 'error' %} <div class="errors" role="alert">{{ message }}</div>{% endif %}
{% endfor %}
{% endif %}
<div class="container">

    <div class="table-responsive-lg">
        <table class="table-dark table-hover; table table-bordered  table-sm  align-middle">
            <thead>
                <tr>
                    <th scope="col-3">CUIT</th>
                    <th scope="col-3">Apellido</th>
                    <th scope="col-4">Nombre</th>
                    <th scope="col">Celular</th>
                    <th scope="col">Telefono Fijo</th>
                    <th scope="col">Calle</th>
                    <th scope="col">Numero</th>
                    <th scope="col">Localidad</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Observaciones</th>
                    <th scope="col">Fecha de ingreso</th>
                    <th scope="col">Vigencia Del Carnet</th>
                    <th scope="col">Patente</th>
                    <th scope="col">Zona</th>
                    <th scope="col">opciones</th>

                </tr>
            </thead>
            <tbody>
                {% for repartidor  in repartidores %}

                <tr>
                    <td scope="row">{{repartidor.CUIT}}</td>
                    <td scope="row">{{repartidor.apellido}}</td>
                    <td scope="row">{{repartidor.nombre}}</td>
                    <td scope="row">{{repartidor.celular}}</td>
                    <td scope="row">{{repartidor.telefono_fijo}}</td>
                    <td scope="row">{{repartidor.calle}}</td>
                    <td scope="row">{{repartidor.numero}}</td>
                    <td scope="row">{{repartidor.localidad}}</td>
                    <td scope="row">{{repartidor.departamento}}</td>
                    <td scope="row">{{repartidor.observaciones}}</td>
                    <td scope="row">{{repartidor.fecha_ingreso_trabajar}}</td>
                    <td scope="row">{{repartidor.vigencia_carnet}}</td>
                    <td scope="row">{{repartidor.patente}}</td>
                    <td scope="row">{{repartidor.zona}}</td>


                    <td scope="row">



                        <a class=" btn btn-info btn-sm" href="{% url 'persona:modificar_repartidor' repartidor.id %}"><i
                                class="bi bi-pencil-square"></i></a>

                        <a class="btn btn-danger btn-sm" href="{% url 'persona:eliminar_repartidor' repartidor.id  %} "
                            onclick="return confirm('¿Está seguro que desea eliminar el registro?')"><i
                                class="bi bi-trash2-fill"></i></a>
                    </td>




                </tr>


                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

apps/persona/templates/persona/modificar_cliente.html
{% extends 'base/base.html' %} {% load static %}
{% block title%}Modifica Cliente{%endblock %}


{% block header%}<h1 class="titulo_pagina">Editar Datos</h1>

<div id="imagen_cliente">
  <img src="{%static  '/img/cliente.png'%}" alt="Foto cliente genericas" />



  <style>
    label {
      color: white !important;
    }
  </style>


</div>{% endblock %}




{% block content%}
<fieldset>
  <legend class="leyenda">Datos Cliente</legend>
  <section>
    <form class="row" action="#" method="POST" id="formulario">
      {% csrf_token %}
      {{form.as_p }}







      <div>
        <button type="submit" class="btn btn-success">Guardar</button>
        <button type="reset" class="btn btn-danger">Cancelar</button> </div>

    </form>
    <section>
</fieldset>

{% endblock %}

apps/persona/templates/persona/modificar_empleado.html
{% extends 'base/base.html' %} {% load static %}
{% block title%}Lista De Clientes{%endblock %}



{% block header%}

<h1 class="titulo_pagina">Editar Empleado</h1>
<div id="foto_delivery"> <img src="{%static  '/img/delivery.png'%}" alt="Imagen delivery"> </div>

<style>
  label {
    color: white !important;
  }
</style>

{%endblock %}


{% block content%}
<fieldset>
  <legend class="leyenda"> Editar Datos</legend>
  <section>

    <form action="#" method="post" enctype="multipart/form-data" class="formulario">
      {% csrf_token %}



      {{empleado.as_p}}

      <div>
        <button type="submit" class="btn btn-success">Guardar</button>
        <button type="reset" class="btn btn-danger">Cancelar</button> </div>


    </form>
  </section>
</fieldset>
{% endblock %}

apps/persona/templates/persona/modificar_repartidor.html
{% extends 'base/base.html' %} {% load static %}



{% block title%}Cadete{%endblock %}






{% block header%}

<style>
    label {
        color: white !important;
    }
</style>

<h1 class="titulo_pagina">FORMULARIO DE REPARTIDOR</h1>
<div id="foto_delivery"> <img src="{%static  '/img/delivery.png'%}" alt="Imagen delivery"> </div>

{%endblock %}



{% if messages %}
{% for message in messages %}
<div class="row">
    <div class="alert {% if message.tags == "success" %}alert-success {% else %}alert-danger{% endif %} alert-dismissible"
        role="alert">
        <button class="close" aria-label="close" data-dismiss="alert" type="button"><span
                aria-hidden="true">x</span></button>
        <p>{{ message|safe }}</p>
    </div>
</div>
{% endfor %}
{% endif %}

{% block content %}



<fieldset>
    <legend class="leyenda">Editar Datos De Repartidor</legend>
    <section>

        <form action="#" method="post" enctype="multipart/form-data" class="formulario">
            {% csrf_token %}



            {{repartidor.as_p }}

            <button type="submit" class="btn btn-success">Guardar</button>
            <button type="reset" class="btn btn-danger">Cancelar</button>


        </form>
    </section>
</fieldset>
<script type="text/javascript" src="{%static 'js/rotiseria.js'%}" defer> </script>
{%endblock %}

apps/persona/templates/persona/repartidor.html
{% extends 'base/base.html' %} {% load static %}



{% block title%}Cadete{%endblock %}






{% block header%}

<style>
    label {
        color: white !important;
    }
</style>

<h1 class="titulo_pagina">REGISTRO DE REPARTIDOR</h1>
<div id="foto_delivery"> <img src="{%static  '/img/delivery.png'%}" alt="Imagen delivery"> </div>

{%endblock %}



{% if messages %}
{% for message in messages %}
<div class="row">
    <div class="alert {% if message.tags == "success" %} alert-success {% else %}alert-danger{% endif %} alert-dismissible"
        role="alert">
        <button class="close" aria-label="close" data-dismiss="alert" type="button"><span
                aria-hidden="true">x</span></button>
        <p>{{ message|safe }}</p>
    </div>
</div>
{% endfor %}
{% endif %}

{% block content %}



<fieldset>
    <legend class="leyenda"> Datos De Repartidor</legend>
    <section>

        <form action="#" method="post" enctype="multipart/form-data" class="formulario">
            {% csrf_token %}



            {{repartidor.as_p }}

            <button type="submit" class="btn btn-success">Guardar</button>
            <button type="reset" class="btn btn-danger">Cancelar</button>


        </form>
    </section>
</fieldset>

{%endblock %}